name: Deploy Docker

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  workflow_run:
    workflows: ["Run Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: |
          sudo docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/Sunday:${{ github.sha }}
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/Sunday:${{ github.sha }}

