name: Deploy Docker

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  workflow_run:
    workflows: ["Run Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: |
          sudo docker login
      
      - name: Build Docker image
        run: |
          sudo docker build . --file Dockerfile --tag djjanko/sunday:${{ github.sha }}
      
      - name: Push Docker image to Docker Hub
        run: |
          sudo docker push djjanko/sunday:${{ github.sha }}

