name: Run Test

on:
  push:
    branches: [main]

jobs:
  check_for_main_cpp:
    name: Check for main.cpp
    runs-on: self-hosted
    steps:
      - name: Check for File
        run: |
          if [ -f "main.cpp" ]; then
            echo "OK" > napaka.txt
          else
            echo "Error: main.cpp not found." > napaka.txt
            exit 1
          fi
      - name: Upload Error File
        uses: actions/upload-artifact@v2
        with:
          name: error
          path: napaka.txt

  prepare_and_run_tests:
    name: Prepare Environment and Run Tests
    needs: check_for_main_cpp
    runs-on: self-hosted
    if: success()
    steps:
      - name: Download Error File
        uses: actions/download-artifact@v2
        with:
          name: error
      - name: Check Error File
        run: |
          if [ -f "napaka.txt" ]; then
            error_content=$(cat napaka.txt)
            if [ "$error_content" == "OK" ]; then
              echo "No error detected. Proceeding with test setup." >> log.txt
            else
              echo "Error: Invalid content in napaka.txt." >> log.txt
              exit 1
            fi
          else
            echo "No error detected. Proceeding with test setup." >> log.txt
          fi
      - name: Setup Test Environment
        run: |
          # Set up the environment for running tests
          sudo apt update
          sudo apt install valgrind -y
          echo "Setting up test environment..." >> log.txt

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          # Compile the test_main.c file
          make
          # Execute the compiled test program
          ./test_main
      
          # Check the contents of result.txt
          if grep -q "SUCCESS" result.txt; then
            echo "SUCCESS" >> log.txt
          else
            echo "FAILED" >> log.txt
          fi
          make clean
